-- =========================================================================
-- TEMPORARY dev OTP pin — always 123456 in simulation mode
-- Run this once. Replaces request_otp() so the client-approval OTP is a fixed
-- 123456 while testing (no SMS gateway needed). When you go live with MSG91,
-- flip sms_live on and the real code is generated by the send-otp Edge Function.
-- Idempotent. Depends on: otp-payments.sql.
-- =========================================================================
create or replace function public.request_otp(p_token uuid, p_phone text)
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
declare q public.quotes; code text; recent int; live boolean;
begin
  select * into q from public.quotes where approval_token = p_token;
  if q.id is null then raise exception 'invalid link'; end if;
  if p_phone is null or length(regexp_replace(p_phone,'[^0-9]','','g')) < 8 then raise exception 'enter a valid phone number'; end if;
  select count(*) into recent from public.quote_otps where quote_id=q.id and created_at > now()-interval '10 minutes';
  if recent >= 5 then raise exception 'too many OTP requests — try again in a few minutes'; end if;
  -- TEMPORARY dev PIN: in simulation the code is always 123456 for easy testing.
  code := '123456';
  insert into public.quote_otps(quote_id, phone, code_hash, expires_at)
    values (q.id, p_phone, extensions.crypt(code, extensions.gen_salt('bf')), now()+interval '10 minutes');
  perform public._notify(q.id,'sms',p_phone,'otp', jsonb_build_object('purpose','approval'));
  live := public._flag('sms_live');
  return jsonb_build_object('sent', true, 'live', live, 'dev_code', case when live then null else code end);
end; $$;
