-- ════════════════════════════════════════════════════════════════════════════
-- HELM — Security audit Phase 3 · P3-02 — FIX (production incident response)
-- Every account whose password is STILL a well-known default (helm, password,
-- admin123, ...) gets:
--   1. a NEW random one-time password (16 chars, generated by the database),
--   2. "must change password" switched on → the app forces them to pick their own
--      password the moment they sign in,
--   3. ALL their sessions ended (anyone already signed in with the old password —
--      including an attacker — is logged out; their open tabs stop refreshing).
-- Only accounts that STILL match a default are touched; running it again changes
-- nothing. No business data is touched — only these logins.
-- The result table shows each email + its one-time password ONCE (it is not
-- stored anywhere). Copy them, then close the tab. Give each real person theirs
-- privately (WhatsApp/call); use the admin one yourself straight away.
-- ════════════════════════════════════════════════════════════════════════════
create temp table if not exists _p3_rotated (email text, role text, one_time_password text);
truncate _p3_rotated;

do $$
declare u record; v_temp text;
begin
  for u in
    select au.id, au.email, p.role
      from auth.users au
      left join public.profiles p on p.id = au.id
     where au.encrypted_password is not null and au.encrypted_password <> ''
       and exists (select 1
                     from unnest(array['helm','Helm','helm123','Helm@123','password','admin','admin123','123456','12345678','demo','test']) d(pw)
                    where au.encrypted_password = extensions.crypt(d.pw, au.encrypted_password))
  loop
    v_temp := translate(encode(extensions.gen_random_bytes(12), 'base64'), '+/=', 'xy9');
    update auth.users
       set encrypted_password = extensions.crypt(v_temp, extensions.gen_salt('bf')),
           updated_at = now()
     where id = u.id;
    update public.profiles set must_change_password = true where id = u.id;
    delete from auth.sessions where user_id = u.id;          -- refresh tokens go with their session
    insert into _p3_rotated values (u.email, u.role, v_temp);
  end loop;
end $$;

select email, role, one_time_password from _p3_rotated order by role nulls last, email;
-- Then re-run P3-CHECK-default-passwords.sql → it must now return "No rows returned".
